[package]
name = "flac-cue-split"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
cue-sys = "2.0.1"
encoding_rs = "0.8.35"
libc = "0.2"
libflac-sys = "0.3.4"
